image:
    name: amazon/aws-cli:2.7.2
    entrypoint: [""]

stages:
    - deploy

.prepare_environments: &prepare_environments
    - |
        SECRET=$( openssl rand -base64 24 );
        echo -e "
        APP_SECRET=$SECRET
        MINIO_ROOT_USER=$AWS_ACCESS_KEY_ID
        MINIO_ROOT_PASSWORD=$AWS_SECRET_ACCESS_KEY
        MINIO_BUCKET=$AWS_S3_BUCKET
        MINIO_REGION=$AWS_DEFAULT_REGION
        MINIO_ENDPOINT_URL=$AWS_S3_ENDPOINT_URL
        MAILER_DSN=gmail://$MAILER_USERNAME:$MAILER_PASSWORD@default
        DATABASE_URL=postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:5432/$DATABASE_DB?serverVersion=14.3&charset=utf8
        CORS_ALLOW_ORIGIN=^https?://([a-z]{1,}\.)?($AWS_EB_INSTANCE_HOST|localhost|127\.0\.0\.1)(:[0-9]+)?$
        JWT_PASSPHRASE=$SECRET
        " >> .env.backend
    - |
        echo -e "
        POSTGRES_DB=$DATABASE_DB
        POSTGRES_USER=$DATABASE_USER
        POSTGRES_PASSWORD=$DATABASE_PASSWORD
        " > .env.database

before_script:
    - echo "AWS_ECR_REGISTRY=$AWS_ECR_REGISTRY" > .env
    - export PATH="/root/.local/bin:${PATH}"
    - yum install -y python37 openssl
    - pip3 install awsebcli
    - aws --version
    - eb --version
    - rm -rf .git

Deploy application:
    stage: deploy
    script:
        - *prepare_environments
        - eb use $AWS_EB_ENVIRONMENT
        - eb status
        - eb deploy
    when: manual
